version: '3.8'

services:
  app:
    # Використовує мереже хоста, щоб контейнер слухав порти безпосередньо на хості
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8080

  app_test:
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - SERVER_PORT=8081
      - SPRING_SERVLET_CONTEXT_PATH=/test

  db:
    image: mysql:8.0.36
    env_file:
      - .env
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: