version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0.36
    env_file:
      - .env
    ports:
      - "3306:3306"
    restart: always