#version: '3.8'
#
#services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "127.0.0.1:8080:8080"
#    env_file:
#      - .env
#    depends_on:
#      - db
#    restart: always
#
#  db:
#    image: mysql:8.0.36
#    env_file:
#      - .env
#    ports:
#      - "3306:3306"
#    restart: always
#    volumes:
#      - mysql-data:/var/lib/mysql
#volumes:
#    mysql-data:
#
#

version: '3.8'

services:
  app:
    # Використовує мереже хоста, щоб контейнер слухав порти безпосередньо на хості
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0.36
    env_file:
      - .env
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

