spring:
  application:
    name: Dekanat
  datasource:
#    url: jdbc:mysql://db:3306/mydb
#    username: root
#    password: rootpassword
    username: ${DB_USER}
    password: ${DB_PASS}
    url: ${DB_URL}
#    url: jdbc:mysql://212.111.203.173:3306/mydb
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
vaadin:
  launch-browser: true

upload:
  dir: /app/uploads