spring:
  application:
    name: Dekanat
  datasource:
    url: ${DB_URL}
    username: ${MYSQL_ROOT_USER}
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  mail:
    host: ${MAIL_HOST:}
    port: ${MAIL_PORT:}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        generate_statistics: false

vaadin:
  launch-browser: true

upload:
  dir: uploads

mail:
  default-from: ${MAIL_DEFAULT_FROM:}

#server:
#  # Порт береться із змінної оточення SERVER_PORT (за замовчуванням 8080)
#  port: ${SERVER_PORT:8080}
#  # Довіряємо заголовкам від проксі (nginx)
#  forward-headers-strategy: framework

logging:
  level:
    root: INFO
    com.esvar.dekanat: DEBUG