spring:
  application:
    name: Dekanat
  datasource:
    url: ${DB_URL}
    username: ${MYSQL_ROOT_USER}
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

vaadin:
  launch-browser: true

upload:
  dir: /app/uploads

#server:
#  # Порт береться із змінної оточення SERVER_PORT (за замовчуванням 8080)
#  port: ${SERVER_PORT:8080}
#  # Довіряємо заголовкам від проксі (nginx)
#  forward-headers-strategy: framework

logging:
  level:
    root: INFO
    com.esvar.dekanat: DEBUG